services:
  - type: web
    name: expertBot
    runtime: node
    rootDir: bot-server
    buildCommand: npm install --no-audit --no-fund
    startCommand: npm start
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
      - key: WEBHOOK_URL
        value: https://expertbot-h9mm.onrender.com/webhook/runrunit
      - key: PORT
        value: 3000
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true